# Generated by Django 4.2.15 on 2024-09-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='default_user', max_length=150),
        ),
    ]
